using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ParsXtmlExamle
{
    /// <summary>
    /// autogenerated class
    /// </summary>
    class DataContext
    {
    }
}
